# Generated by Django 5.1.15 on 2026-05-09 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_remove_studentprofile_next_funding_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=255)),
                ('iban', models.CharField(max_length=64)),
                ('edrpou', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetFinanceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('scholarship_status', models.CharField(max_length=255)),
                ('next_funding_date', models.DateField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget_finance', to='accounts.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PaidFinanceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuition_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_debt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_deadline', models.DateField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paid_finance', to='accounts.studentprofile')),
            ],
        ),
    ]
