# Generated by Django 5.1.15 on 2026-05-09 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=32)),
                ('specialization', models.CharField(max_length=64)),
                ('funding_type', models.CharField(choices=[('budget', 'Budget'), ('contract', 'Contract')], max_length=32)),
                ('scholarship_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('scholarship_status', models.CharField(blank=True, max_length=128)),
                ('next_funding_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
