# Generated by Django 5.1.15 on 2026-05-09 12:18

import django.db.models.deletion
from django.db import migrations, models


def migrate_legacy_task2_registration_data(apps, schema_editor):
    user_model = apps.get_model("accounts", "User")
    student_profile_model = apps.get_model("accounts", "StudentProfile")
    registration_finance_payload_model = apps.get_model("accounts", "RegistrationFinancePayload")

    for profile in student_profile_model.objects.select_related("user").all():
        user = user_model.objects.get(pk=profile.user_id)

        if not profile.full_name and user.full_name:
            profile.full_name = user.full_name

        legacy_funding_type = profile.funding_type
        normalized_funding_type = "paid" if legacy_funding_type == "contract" else legacy_funding_type
        if normalized_funding_type != profile.funding_type:
            profile.funding_type = normalized_funding_type

        legacy_payload = {}
        if profile.scholarship_amount is not None:
            legacy_payload["scholarship_amount"] = str(profile.scholarship_amount)
        if profile.scholarship_status:
            legacy_payload["scholarship_status"] = profile.scholarship_status
        if profile.next_funding_date is not None:
            legacy_payload["next_funding_date"] = profile.next_funding_date.isoformat()

        profile.save(update_fields=["full_name", "funding_type"])

        if legacy_payload:
            registration_finance_payload_model.objects.update_or_create(
                profile_id=profile.pk,
                defaults={
                    "payload": {
                        "legacy_funding_type": legacy_funding_type,
                        "normalized_funding_type": normalized_funding_type,
                        **legacy_payload,
                        "migrated_from_legacy_task2": True,
                    }
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_full_name_studentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationFinancePayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_finance_payload', to='accounts.studentprofile')),
            ],
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.RunPython(
            migrate_legacy_task2_registration_data,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='next_funding_date',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='scholarship_amount',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='scholarship_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='funding_type',
            field=models.CharField(choices=[('budget', 'Budget'), ('paid', 'Paid')], max_length=32),
        ),
    ]
