# Generated by Django 5.1.15 on 2026-05-09 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_chatmessage_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[],
            options={
                "verbose_name": "Reminder",
                "verbose_name_plural": "Reminders",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("chat.chatmessage",),
        ),
    ]
