# Generated by Django 5.1.15 on 2026-05-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_reminder_proxy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatgroup",
            name="group_type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("reminders", "Reminders"),
                    ("study_group", "Study Group"),
                    ("direct", "Direct"),
                ],
                max_length=30,
            ),
        ),
    ]
